name: Mail Action

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  read_mail:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install imaplib2 python-telegram-bot

      - name: Read emails
        env:
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          import imaplib
          import email
          from email.header import decode_header
          import time
          from datetime import datetime

          # Connect to Gmail IMAP server
          mail = imaplib.IMAP4_SSL('imap.gmail.com')
          mail.login(GMAIL_USER, GMAIL_PASSWORD)
          mail.select('inbox')

          # Load last checked time
          try:
              with open('last_checked.txt', 'r') as f:
                  last_checked = f.read().strip()
          except FileNotFoundError:
              last_checked = '1970-01-01 00:00:00'

          # Fetch latest emails
          result, data = mail.search(None, 'ALL')
          email_ids = data[0].split()[-10:]  # Get latest 10 emails

          for e_id in email_ids:
              result, msg_data = mail.fetch(e_id, '(RFC822)')
              msg = email.message_from_bytes(msg_data[0][1])
              email_date = msg['Date']
              email_subject, encoding = decode_header(msg['Subject'])[0]

              if isinstance(email_subject, bytes):
                  email_subject = email_subject.decode(encoding if encoding else 'utf-8')

              if '新短信' in email_subject:
                  if time.mktime(email.utils.parsedate(email_date)) > time.mktime(email.utils.parsedate(last_checked)):
                      email_body = msg.get_payload(decode=True).decode()
                      # Send to Telegram
                      import requests
                      message = f"{email_date} - {email_subject}\n{email_body}"
                      requests.post(f"https://api.telegram.org/bot{TELEGRAM_TOKEN}/sendMessage", data={"chat_id": TELEGRAM_CHAT_ID, "text": message})

          # Update last checked time
          with open('last_checked.txt', 'w') as f:
              f.write(datetime.now().strftime('%Y-%m-%d %H:%M:%S'))

      - name: Commit last checked time
        run: |
          echo "$(date)" > time.txt
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add time.txt
          git commit -m "Update last checked time"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
