name: Mail Action

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  read_mail:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install imaplib2 requests python-telegram-bot

      - name: Read emails
        env:
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python read_email.py

      - name: Commit last checked time
        run: |
          echo "$(date)" > time.txt
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add time.txt
          git commit -m "Update last checked time" || echo "No changes to commit"
          git pull origin main --rebase  # 拉取远程更改并重新应用本地更改
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

